[build]
  base = "next/"
  command = "echo 'hello Netlify build'"
  publish = "next/out"
  functions = "next/functions"

[[plugins]]
  package = "plugins/api"
  [plugins.inputs]
    exclude = ["/search.html"]