[build]
  base = "next/"
  command = "yarn build:site"
  publish = "out"
  functions = "next/functions"


[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[plugins]]
  package = "./plugins/prepare/index.js"
  [plugins.inputs]
    appFolder = "app"

[[plugins]]
  package = "./plugins/api/index.js"
  [plugins.inputs]
    exclude = ["/search.html"]